export const USER_FOUND = "USER_FOUND";
export const USER_COUNT_FOUND = "USER_COUNT_FOUND";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const REF_USER_LIST_FOUND = "REF_USER_LIST_FOUND";
export const USER_CREATED = "USER_CREATED";
export const USER_CREATED_WITH_REF = "USER_CREATED_WITH_REF";
export const PINK_SELL_ORDER_CREATE = "PINK_SELL_ORDER_CREATE";
